if: tags = true

# Export variables
env:
  - tf_version=0.12.19 tf_init_cli_options="-input=false" tf_validation_cli_options="" tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve -input=false"

services:
  - docker

before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip

jobs:
  include:
    - stage: build
      script: bash ./build.sh microsoft-vote-front
    - stage: terraform plan
      script:
        - cd aks_cluster
        - terraaform init $tf_init_cli_options
        - terraform validate $tf_validation_cli_options
        - terraform plan $tf_plan_cli_options
        - cd ../
    - stage: terraform apply
      script:
        - cd aks_cluster
        - terraform init $tf_init_cli_options
        - terraform apply $tf_apply_cli_options
        - cd ../
    - stage: deploy
    - script: bash ./deploy.sh