sudo: required
# Export variables
env:
  - tf_version=1.0.3 tf_init_cli_options="-input=false" tf_validation_cli_options="" tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve -input=false"

services:
  - docker

before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.20.7/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli

jobs:
  include:
    - stage: build
      script: bash ./build.sh microsoft-vote-front
      if: tag IS present
    - stage: terraform plan
      script:
        - cd aks_cluster
        - terraform init $tf_init_cli_options
        - terraform validate $tf_validation_cli_options
        - terraform plan -var "client_id=$client_id" -var "subscription_id=$subscription_id" -var "tenant_id=$tenant_id" -var "client_secret=$client_secret" $tf_plan_cli_options
        - cd ../
    - stage: terraform apply
      script: bash ./terraform_apply.sh
    - stage: deploy
      script: bash ./deploy.sh testResourceGroup aksCluster