# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: 
  displayName: Provision Infra
  jobs:
  - job: Terraform
    displayName: Terraform
    pool: Self-hosted
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: CmdLine@2
      displayName: Terraform Init
      inputs:
        script: |
          cd $(System.DefaultWorkingDirectory)/infra/terraform/eks
          terraform init
    - task: CmdLine@2
      displayName: Terraform Run
      inputs:
        script: |
          cd $(System.DefaultWorkingDirectory)/infra/terraform/eks
          terraform apply -auto-approve -var-file="$(System.DefaultWorkingDirectory)/infra/terraform/eks/demo.tfvars"

- stage: BuildAndPush
  displayName: Build & Push image
  jobs:
  - job: Build
    displayName: Build
    pool: Self-hosted
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: 'azure-vote'
        dockerfile: 'azure-vote/Dockerfile'
        tags: |
          $(tag)
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-wellszhang'
        regionName: 'ap-southeast-2'
        imageSource: 'imagename'
        sourceImageName: 'azure-vote'
        sourceImageTag: '$(tag)'
        repositoryName: 'azure-vote'
        pushTag: '$(tag)'
        autoCreateRepository: true

- stage:      
  displayName: Install k8s Dashboard
  jobs:
  - job: 
    displayName: Install k8s Dashboard
    pool: Self-hosted
    steps: 
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here 
          helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
          helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard

- stage: 
  displayName: Deploy Service
  jobs:
  - deployment: DeploySvc
    displayName: Deploy Service to EKS
    pool: Self-hosted
    environment: Development
    strategy:
    # Default deployment strategy, more coming...
      runOnce:
        deploy:
          steps:
          - task: AWSCLI@1
            displayName: update-kubeconfig
            inputs:
              awsCredentials: 'aws-wellszhang'
              regionName: 'ap-southeast-2'
              awsCommand: 'eks'
              awsSubCommand: 'update-kubeconfig'
              awsArguments: '--region ap-southeast-2 --name eks-dev-7KXINSCx'       

          - task: Kubernetes@1
            displayName: kubectl get service
            inputs:
              connectionType: 'None'
              namespace: 'kube-system'
              command: 'get'
              arguments: 'svc'
              
          - task: Kubernetes@1
            displayName: kubectl apply
            inputs:
              connectionType: 'None'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: '$(System.DefaultWorkingDirectory)/azure-vote-all-in-one-redis.yaml'
              outputFormat: 'yaml'
