# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pr: none

resources:
- repo: self

variables:
  - name: 'tag'
    value: '$(Build.BuildId)'

stages:
- stage: 
  displayName: Provision Infra
  jobs:
  - job: Terraform
    displayName: Terraform
    pool: Self-hosted
    steps:
    - task: oneLuckiDevJson2Variable@1
      inputs:
        jsonFile: '$(System.DefaultWorkingDirectory)/variables/variables_$(EnvShort).json'
        shouldPrefixVariables: false
        
    - task: replacetokens@5
      inputs:
        rootDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform'
        targetFiles: '**/*.tf'
        encoding: 'auto'
        tokenPattern: 'default'
        writeBOM: true
        actionOnMissing: 'fail'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        useLegacyPattern: false
        enableTelemetry: true
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: CmdLine@2
      displayName: Terraform Init
      inputs:
        script: |
          cd $(System.DefaultWorkingDirectory)/infra/terraform/eks
          terraform init
    - task: CmdLine@2
      displayName: Terraform Run
      inputs:
        script: |
          cd $(System.DefaultWorkingDirectory)/infra/terraform/eks
          terraform apply -auto-approve -var-file="$(System.DefaultWorkingDirectory)/infra/terraform/eks/tf_$(EnvShort).tfvars"

- stage: BuildAndPush
  displayName: Build & Push image
  jobs:
  - job: Build
    displayName: Build
    pool: Self-hosted
    steps:
    - task: oneLuckiDevJson2Variable@1
      inputs:
        jsonFile: '$(System.DefaultWorkingDirectory)/variables/variables_$(EnvShort).json'
        shouldPrefixVariables: false

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: 'azure-vote'
        dockerfile: 'azure-vote/Dockerfile'
        tags: |
          $(tag)
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-wellszhang'
        regionName: '$(AwsRegion)'
        imageSource: 'imagename'
        sourceImageName: 'azure-vote'
        sourceImageTag: '$(tag)'
        repositoryName: 'azure-vote'
        pushTag: '$(tag)'
        autoCreateRepository: true

- stage:      
  displayName: Install k8s Dashboard
  jobs:
  - job: 
    displayName: Install k8s Dashboard
    pool: Self-hosted
    steps: 
    - task: oneLuckiDevJson2Variable@1
      inputs:
        jsonFile: '$(System.DefaultWorkingDirectory)/variables/variables_$(EnvShort).json'
        shouldPrefixVariables: false

    - task: AWSCLI@1
      displayName: update-kubeconfig
      inputs:
        awsCredentials: 'aws-wellszhang'
        regionName: '$(AwsRegion)'
        awsCommand: 'eks'
        awsSubCommand: 'update-kubeconfig'
        awsArguments: '--region $(AwsRegion) --name $(EksName)' 

    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here 
          helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
          helm uninstall kubernetes-dashboard
          helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard

- stage: 
  displayName: Deploy Service
  jobs:
  - deployment: DeploySvc
    displayName: Deploy Service to EKS
    pool: Self-hosted
    environment: $(EnvLong)
    strategy:
    # Default deployment strategy, more coming...
      runOnce:
        deploy:
          steps:
          - task: oneLuckiDevJson2Variable@1
            inputs:
              jsonFile: '$(System.DefaultWorkingDirectory)/variables/variables_$(EnvShort).json'
              shouldPrefixVariables: false
          
          - task: AWSCLI@1
            displayName: update-kubeconfig
            inputs:
              awsCredentials: 'aws-wellszhang'
              regionName: '$(AwsRegion)'
              awsCommand: 'eks'
              awsSubCommand: 'update-kubeconfig'
              awsArguments: '--region $(AwsRegion) --name $(EksName)'       

          - task: Kubernetes@1
            displayName: kubectl get service
            inputs:
              connectionType: 'None'
              namespace: 'kube-system'
              command: 'get'
              arguments: 'svc'
              
          - task: Kubernetes@1
            displayName: kubectl apply
            inputs:
              connectionType: 'None'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: '$(System.DefaultWorkingDirectory)/azure-vote-all-in-one-redis.yaml'
              outputFormat: 'yaml'
