apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
      annotations:
        config.linkerd.io/proxy-cpu-request: "0.1"
    spec:
      containers:
      - name: azure-vote-back
        image: natzkadevcontainerregistry.azurecr.io/azure-vote-back:latest
        #mcr.microsoft.com/oss/bitnami/redis:6.0.8
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            # memory: 200Mi
          limits:
            cpu: 1
            # memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  ports:
  - port: 80
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-vote-front
      annotations:
        config.linkerd.io/proxy-cpu-request: "0.1"
    spec:
      containers:
      - name: azure-vote-front
        image: natzkadevcontainerregistry.azurecr.io/azure-vote-front:latest
        # mcr.microsoft.com/azuredocs/azure-vote-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            # memory: 200Mi
          limits:
            cpu: 500m
            # memory: 2Gi
        env:
        - name: COMPUTING_BK
          value: "http://azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front


---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: azure-vote-back
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-vote-back
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # - type: Pods
  #   pods:
  #     metric:
  #       name: packets-per-second
  #     target:
  #       type: AverageValue
  #       averageValue: 1k
  # - type: Object
  #   object:
  #     metric:
  #       name: requests-per-second
  #     describedObject:
  #       apiVersion: networking.k8s.io/v1beta1
  #       kind: Ingress
  #       name: azure-vote-front
  #     target:
  #       type: Value
  #       value: 1k