# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Self-hosted
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: 'azure-vote'
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tags: |
          $(tag)
      
- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    pool: Self-hosted
    steps:
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-wellszhang'
        regionName: 'ap-southeast-2'
        imageSource: 'imagename'
        sourceImageName: 'azure-vote'
        sourceImageTag: '$(tag)'
        repositoryName: 'azure-vote'
        pushTag: '$(tag)'
        autoCreateRepository: true
