# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: 
  displayName: Provision Infra
  jobs:
  - job: Terraform
    displayName: Terraform
    pool: Self-hosted
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/eks'
        backendServiceAWS: 'aws4terraform'
        backendAWSBucketName: 'tfe-state-demo'
        backendAWSKey: 'tf'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/eks'
        commandOptions: '-var-file="$(System.DefaultWorkingDirectory)/infra/terraform/eks/demo.tfvars"'
        environmentServiceNameAWS: 'aws4terraform'  
    - task: TerraformTaskV2@2
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra/terraform/eks'
        commandOptions: '-var-file="$(System.DefaultWorkingDirectory)/infra/terraform/eks/demo.tfvars" -auto-approve'
        environmentServiceNameAWS: 'aws4terraform'
        
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Self-hosted
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: 'azure-vote'
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tags: |
          $(tag)
      
- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    pool: Self-hosted
    steps:
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-wellszhang'
        regionName: 'ap-southeast-2'
        imageSource: 'imagename'
        sourceImageName: 'azure-vote'
        sourceImageTag: '$(tag)'
        repositoryName: 'azure-vote'
        pushTag: '$(tag)'
        autoCreateRepository: true
