apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: damian.urbaniak@natzka.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: predscaling01-cert
  namespace: default
spec:
  secretName: predscaling01-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "predscaling01.natzkalabs.com"
  # secretTemplate:
  #   annotations:
  #     kubed.appscode.com/sync: "cert-manager-tls=true"

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: predscaling01-graf-cert
  namespace: monitoring
spec:
  secretName: predscaling01-graf-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "predscaling01-graf.natzkalabs.com"

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: predscaling01-prom-cert
  namespace: monitoring
spec:
  secretName: predscaling01-prom-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "predscaling01-prom.natzkalabs.com"