name: Docker Image CI
on:  
  push:
    tags:
    - 'v*'
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: ${{ secrets.ACR_SERVER }}
    - name: Build and push Docker image
      run: |
        docker buildx create --name mybuilder --driver docker-container --platform linux/amd64,linux/arm64 --bootstrap --use
        docker buildx build --platform linux/amd64,linux/arm64 --tag ${{ secrets.ACR_SERVER }}/azure-vote-front:$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)') --push ./azure-vote